### ISSUE TITLE
'add child to list' is not working when using multiple lists in one document

### ISSUE THREAD

**Issue by ax-sc** [desklab/doku#1]
There is a bug when using multiple lists in one document. It is not possible to create items for the second list. Instead of creating a element in the second list when clicking on *add child* and then *save*, no changes are visible. When opening the *add child* dialog of the first list, the *name* is marked as missing, so i´m suspecting that doku was trying to create an element in the first list. 

**steps to reproduce:**
1. create a new document
2. add two lists to template
3. Try to create an element in the second list

**template:**
```html
<html>
<head>
  <title>{{ title }}</title>
  <meta charset="utf-8">
</head>
<body>
  {% for element in first_list %}
  	{{ element }}
  {% endfor %}
  
  {% for element in second_list %}
  	{{ element }}
  {% endfor %}
</body>
</html>
```

**Comment by 3j14** [comment]
Fixed in f38ff5e27fb3e12bd6770a29e3f9bee511a0bb09
