### ISSUE TITLE
order of list-elements

### ISSUE THREAD

**Issue by ax-sc** [desklab/doku#13]
The order of list elements seems to be dependent on the sequence of creating and saving the childs/elements but not completely ordered by last-modified. The name of the child/element seems to have an additional effect on the order but the the list elements are not fully ordered by name. This leads to some unpredictable/not expected behaviour when working with lists.

The order of the elements of lists should be more predictable/controllable. The optimal solution would be to be able to drag-and-drop elements inside a list to reorder them. One temporary solution could be to order the elements by name. The sequence of saving/creating childs for a list sould not affect the order. At least the temporary solution should be implemented before the first release, any further enhancement may be postponed to later versions.

**Comment by 3j14** [comment]
Currently, the elements are in no particular order. Thus, their order is completely random. We should implement a parameter for ordering (e.g. `?order=field` where field denotes to the name of the model field) and additionally implement pagination (e.g. `?p=1`) for long lists. Pagination is part of Flask-SQLAlchemy whereas sorting is part of SQLAlchemy.
