### ISSUE TITLE
hyphens and dots in variable-names

### ISSUE THREAD

**Issue by ax-sc** [desklab/doku#24]
Compiling a document with a **variable name containing a hyphen** fails. Implement the use of hyphens or catch their appearence and show a dialog to the user while removing them automatically.

Here is the corresponding Sentry summary:
> TypeError document.render
> unsupported operand type(s) for -: 'str' and 'str'
> mechanism: flask
> handled: no

Compiling a document with a **variable name containing a dot** works but everything after the `.` is ignored. Implement the use of dots or catch their appearence and show a dialog to the user while removing them and the following letters automatically.

Here is the corresponding Sentry summary:
> TemplateSyntaxError api.v1.template.update
> expected token 'end of print statement', got ':'
> mechanism: flask
> handled: no

**Comment by 3j14** [comment]
16526ef should fix this 😉

**Comment by 3j14** [comment]
Changes should be up soon. Closing for now
