### ISSUE TITLE
unable to rename and/or change template in document settings

### ISSUE THREAD

**Issue by ax-sc** [desklab/doku#31]
Drop-down-menu to change templates in document settings shows no options. Saving document settings fails. As a consequence, renaming documents also fails.

**Comment by 3j14** [comment]
This is due to the fact that the API returns a pagination (`meta`) and a data (`result`) object whereas previously, the data object has been the response itself. This has to be adjusted in the JavaScript API client.

**Comment by 3j14** [comment]
As the Template input is empty, the submitted form data is invalid and thus the name can not be changed
