### ISSUE TITLE
renaming a document fails

### ISSUE THREAD

**Issue by ax-sc** [desklab/doku#40]
Renaming a document fails (the loading icon is not resolved). The developer´s console shows the following error:
```
TypeError: this.$refs.documentPublicInput is undefined
    save https://doku.desk-lab.de/static/edit.bundle.js:8
    Ve https://doku.desk-lab.de/static/vendor.bundle.js:13
    n https://doku.desk-lab.de/static/vendor.bundle.js:13
    _wrapper https://doku.desk-lab.de/static/vendor.bundle.js:13
```
Before 1bbd194de348cc2f520123306c4027b50043a36e, we had an animated-toggle element to change the visibility of the document (public - private). This element was removed, but the save-process still expects a value for the input.

**Comment by 3j14** [comment]
Should be fixed now ;) sorry for the late response
