### ISSUE TITLE
add support for formulas

### ISSUE THREAD

**Issue by ax-sc** [desklab/doku#41]
Extend support for complex formulas including fractions etc.. Maybe we can use https://pypi.org/project/markdown-katex/ to process tex-like variables to html?

**Comment by ax-sc** [comment]
Formulas are working now (thanks @jnsdrtlf !). Maybe we should think about adding some documentation framework and show some exemplary use of the different features as more of them become usable in *doku* or at least extend the Readme?

**Comment by 3j14** [comment]
Documentation for doku :D Sounds good! I would prefer Sphinx and I'll look into it. Would also be great for `gcampus` :)
