### ISSUE TITLE
add feature to download the html version of a document

### ISSUE THREAD

**Issue by ax-sc** [desklab/doku#45]
Can we introduce a feature to be able to download the html in it´s latest version before it is printed to a pdf by weasyprint? This feature would be helpfull when debugging complex Jinja-templates (after processing the markdown-variables) in combination with stylesheets. 

FYI: I assume that https://github.com/desklab/doku-styles/issues/9 is caused by an additional html element introduced by the way we convert the variables and would like to check the 'final' html.

**Comment by 3j14** [comment]
You can now append `/html` to the url when editing a document. Similar to `/render`, this will return the HTML output of the Jinja Template. Should be only used for debugging purposes and is thus not available from the UI.

**Comment by 3j14** [comment]
**Example:**

**https://doku.desk-lab.de/document/83/html**

**Comment by 3j14** [comment]
Note that this is before resolving any URLs. Resources such as SVGs will be placed by WeasyPrint and are thus not available at this point.
